### ISSUE TITLE
multibarHorizontal doesn't render values when using showValues option when using wkhtmltopdf 

### ISSUE THREAD

**Issue by pixelsailor** [nvd3-community/nvd3#10] opened 2015-01-07 17:50 UTC
Details at http://stackoverflow.com/questions/27825225/nvd3-renders-charts-differently-when-printed

Really perplexed by this. Charts are rendering differently depending on the output. I've noticed it with the line charts. And likely related, multiBarHorizontal doesn't show text when showValues is set to true, but only when saved to PDF again. When rendered in a browser, they show up fine.

Could this possibly be an issue with D3 itself?

**Comment by liquidpele** [comment] 2015-01-07 18:16
wkhtmltopdf isn't rendering it quite the same is all, it's all on that project.  Since it uses qtwebkit, there are likely differences between that webkit fork and the heavily modified fork used by Google/Opera/etc.

**Comment by liquidpele** [comment] 2015-01-07 18:18
Also the code you use to generate it, and the height and width differ, and D3 will adjust axis based on those, so the comparison isn't even completely valid to begin with.

**Comment by pixelsailor** [comment] 2015-01-07 18:46
The issue isn't about the grid lines though. In the example linked wkhtmltopdf is rendering circles at each data point and the browser version lacks them. I actually prefer the wkhtmltopdf version so an option to include such markers would be a welcome addition.

I'm not entirely convinced this is a wkhtmltopdf issue. In regards to the showValues() method, when enabled on discreteBarChart, the values show up in PDF as expected. It only affects multiBarHorizontal. That said, I haven't gone over the differences in source between those two so I can't say if one's doing something that the other isn't.

**Comment by liquidpele** [comment] 2015-01-07 19:55
The circles thing I can't reproduce, I imagine it's probably a CSS3 thing that the rendering engine differs on as far as supporting things.  I'd certainly welcome a pull request for an option to show the points though... they're actually points of a scatter chart on top of the line chart so you can even use the point* options for them to control how they look. 

http://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart

Only discreteBar will show the values above each bar as it's meant for a very simplistic bar chart with few items, the other bar charts rely in tooltips.

**Comment by pixelsailor** [comment] 2015-01-07 20:06
Tracked down the lack of showValues() on rendered horizontal bars. Line 221 of multiBarHorizontal.js reads

    .html(function(d,i) {

should be

    .text(function(d,i) {

Considering that this only affects wkhtmltopdf you're probably right in that it's an issue with their code. That change matches the code for discreteBar though and assuming it doesn't negatively impact something else, that seems to be the fix.

**Comment by liquidpele** [comment] 2015-01-07 20:14
Oh, so multibarHorizontal has that option too, I thought only discreteBar did, interesting. 

It should be text I think, since that's within the svg on a text object, so I wouldn't think html is valid there...  feel free to send me a pull request on the development branch to fix that, or I'll fix it when I have some time this weekend.

**Comment by liquidpele** [comment] 2015-01-07 20:49
Re-opening since the .html() should be .text() as Ben discovered.

**Comment by liquidpele** [comment] 2015-01-09 00:33
Should be fixed now, in dev branch.

**Closed by liquidpele** 2015-01-09 00:33 UTC
Labels: bug
